# Generated by Django 5.2.1 on 2025-10-26 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warga', '0002_pengaduan'),
    ]

    operations = [
        migrations.RenameField(
            model_name='warga',
            old_name='no_telpon',
            new_name='no_telepon',
        ),
        migrations.AlterField(
            model_name='pengaduan',
            name='status',
            field=models.CharField(choices=[('BARU', 'Baru'), ('DIPROSES', 'Diproses'), ('SELESAI', 'Selesai')], default='BARU', max_length=10),
        ),
        migrations.AlterField(
            model_name='warga',
            name='nik',
            field=models.CharField(max_length=16, unique=True, verbose_name='Nomor Induk Kependudukan'),
        ),
    ]
